Repository yarnpkg/berry, pull requests merged in 2022-09, with the labels that each got.

#4698 refactor(init)!: disable zero-installs by default
  .yarn/versions/98ca843d.yml
  CHANGELOG.md
  packages/plugin-init/sources/commands/init.ts
Labels: major

#4839 docs: mention zero-installs repo size
  packages/gatsby/content/features/zero-installs.md
Labels: documentation

#4854 chore(playground): fix cors issue
  packages/gatsby/playground-sandbox/constants.js
  packages/gatsby/playground-sandbox/cors.js
  packages/gatsby/playground-sandbox/package.json
  packages/gatsby/playground-sandbox/pages/api/check-repo.js
  packages/gatsby/playground-sandbox/pages/api/clone-repo.js
  packages/gatsby/playground-sandbox/pages/api/fetch-node-version.js
  packages/gatsby/playground-sandbox/pages/api/sherlock.js
  packages/gatsby/playground-sandbox/pages/index.js
Labels: playground

#4865 refactor(plugin-link)!: rename resolvers and fetchers
  .yarn/versions/4df7cbc6.yml
  CHANGELOG.md
  packages/plugin-link/sources/LinkFetcher.ts
  packages/plugin-link/sources/LinkResolver.ts
  packages/plugin-link/sources/PortalFetcher.ts
  packages/plugin-link/sources/PortalResolver.ts
  packages/plugin-link/sources/RawLinkResolver.ts
  packages/plugin-link/sources/constants.ts
  packages/plugin-link/sources/index.ts
Labels: major

#4853 refactor!: move `ZipFS` and `ZipOpenFS` into `@yarnpkg/libzip`
  .pnp.cjs
  .yarn/versions/5be37cc3.yml
  packages/plugin-file/package.json
  packages/plugin-file/sources/fileUtils.ts
  packages/plugin-nm/sources/NodeModulesLinker.ts
  packages/plugin-nm/sources/PnpLooseLinker.ts
  packages/plugin-patch/sources/PatchFetcher.ts
  packages/vscode-zipfs/sources/ZipFSProvider.ts
  packages/yarnpkg-core/sources/Cache.ts
  packages/yarnpkg-core/sources/Configuration.ts
  packages/yarnpkg-core/sources/scriptUtils.ts
  packages/yarnpkg-core/sources/tgzUtils.ts
  packages/yarnpkg-core/sources/worker-zip/Worker.ts
  packages/yarnpkg-core/tests/TestPlugin.ts
  packages/yarnpkg-fslib/sources/MountFS.ts
  packages/yarnpkg-fslib/sources/constants.ts
  packages/yarnpkg-fslib/sources/index.ts
  packages/yarnpkg-fslib/tests/patchedFs.test.ts
  packages/yarnpkg-libzip/package.json
  packages/yarnpkg-libzip/sources/ZipFS.ts
  packages/yarnpkg-libzip/sources/ZipOpenFS.ts
  packages/yarnpkg-libzip/sources/async.ts
  packages/yarnpkg-libzip/sources/common.ts
  packages/yarnpkg-libzip/sources/instance.ts
  packages/yarnpkg-libzip/sources/makeInterface.ts
  packages/yarnpkg-libzip/sources/mountMemoryDrive.ts
  packages/yarnpkg-libzip/sources/sync.ts
  packages/yarnpkg-libzip/tests/ZipFS.test.ts
  packages/yarnpkg-libzip/tests/ZipOpenFS.test.ts
  packages/yarnpkg-libzip/tests/fixtures/folder.zip/foo.zip
  packages/yarnpkg-libzip/tests/fixtures/foo.hiddenzip
  packages/yarnpkg-libzip/tests/fixtures/foo.zip
  packages/yarnpkg-pnp/sources/loader/_entryPoint.ts
  packages/yarnpkg-pnp/tests/pnpStandardRunner.test.ts
  yarn.lock
Labels: major

#4899 refactor!: cleanup lutimes
  .pnp.cjs
  .yarn/versions/57a58394.yml
  CHANGELOG.md
  packages/plugin-patch/sources/tools/apply.ts
  packages/yarnpkg-core/sources/tgzUtils.ts
  packages/yarnpkg-core/sources/worker-zip/index.js
  packages/yarnpkg-fslib/sources/FakeFS.ts
  packages/yarnpkg-fslib/sources/MountFS.ts
  packages/yarnpkg-fslib/sources/NoFS.ts
  packages/yarnpkg-fslib/sources/NodeFS.ts
  packages/yarnpkg-fslib/sources/ProxiedFS.ts
  packages/yarnpkg-fslib/sources/algorithms/copyPromise.ts
  packages/yarnpkg-pnp/sources/hook.js
  packages/yarnpkg-pnpify/sources/NodeModulesFS.ts
Labels: major
